version: '3.4'
services:
  typesense:
    image: typesense/typesense:0.25.2
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=336dd9f5-0fc8-478b-b7ac-06b88ca03dc3 --enable-cors'
